questao4:
	clear
	g++ questao4.cpp -lm -O2 -std=c++11
	clear
	./a.out
questao5:
	clear
	g++ questao5.cpp -lm -O2 -std=c++11
	clear
	./a.out
questao6:
	clear
	g++ questao6.cpp -lm -O2 -std=c++11
	clear
	./a.out
questao7:
	clear
	g++ questao7.cpp -lm -O2 -std=c++11
	clear
	cat palavras.txt | ./a.out
