questao4:
	clear
	g++ questao4.cpp -std=c++11 -lm -Wall
	clear
	cat input4.txt | ./a.out
questao5:
	clear
	g++ questao5.cpp -std=c++11 -lm -Wall
	clear
	cat input5.txt | ./a.out
questao6:
	clear
	g++ questao6.cpp -std=c++11 -Wall -O2 -lm
	clear
	cat input6.txt | ./a.out
