q4:
	clear
	g++ 4.cpp -std=c++11 -o 4.out
	clear
	./4.out
q5:
	clear
	g++ 5.cpp -std=c++11 -o 5.out
	clear
	./5.out
q7:
	clear
	g++ 7.cpp -std=c++11 -o 7.out
	clear
	./7.out
q12:
	clear
	g++ 12.cpp -std=c++11 -o 12.out
	clear
	./12.out
q13:
	clear
	g++ 13.cpp -std=c++11 -o 13.out
	clear
	./13.out
clean:
	rm *.out
