questao1:
	clear
	g++ questao1.cpp -o questao1 -std=c++11
	clear
	./questao1
questao2:
	clear
	g++ questao2.cpp -o questao2 -std=c++11
	clear
	./questao2 < palavras.txt
questao3:
	clear
	g++ questao3.cpp -o questao3 -std=c++11
	clear
	./questao3
questao4:
	clear
	g++ arvore_avl.cpp -o arvore_avl
	g++ arvore_VP.cpp -o arvore_VP
	clear
	./arvore_avl
	./arvore_VP
